name: rethinking

channels:
  - conda-forge

dependencies:
  - python=3.10
  - pymc>=4.2.1
  - jupyter>=1.0.0,<2
  - notebook>=6.4.8,<7
  # - ipykernel=6.9.1
  - scipy>1.8.0,<9
  - matplotlib>3.5.1,<4
  - seaborn>0.11,<1
  - jax
  - sf-hamilton>=1.8.0,<2
  - pandas-profiling
  - scikit-learn=1.1.2