name: rethinking

channels:
  - conda-forge

dependencies:
  - python=3.8.5
  - pymc3=3.11.4
  - jupyter=1.0.0
  - notebook=6.4.8
  - ipykernel=6.9.1
  - mkl-service=2.4.0
  - scipy=1.8.0
  - matplotlib=3.5.1
